sudo: required
services:
  - docker

before_install:
  - docker build -t kent426/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kent426/react-test npm test

after_success:
  - docker build -t kent426/multi-client ./client
  - docker build -t kent426/multi-nginx  ./nginx
  - docker build -t kent426/multi-server ./server
  - docker build -t kent426/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push kent426/multi-client
  - docker push kent426/multi-nginx
  - docker push kent426/multi-server
  - docker push kent426/multi-worker
